/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#5e5e5e',
        'tertiary-fixed-dim': '#c6c6c7',
        'primary-fixed': '#e2e2e2',
        'tertiary-container': '#1a1c1c',
        surface: '#f9f9f9',
        'surface-dim': '#dadada',
        'on-secondary-container': '#626262',
        'on-secondary-fixed': '#1b1c1c',
        error: '#ba1a1a',
        'outline-variant': '#cfc4c5',
        'surface-container-low': '#f3f3f3',
        outline: '#7e7576',
        'on-secondary-fixed-variant': '#464747',
        'on-primary-fixed': '#1b1b1b',
        'surface-container': '#eeeeee',
        'surface-variant': '#e2e2e2',
        'secondary-fixed-dim': '#c7c6c6',
        'primary-fixed-dim': '#c6c6c6',
        'surface-bright': '#f9f9f9',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'on-tertiary-fixed-variant': '#454747',
        'on-error': '#ffffff',
        'on-secondary': '#ffffff',
        'inverse-primary': '#c6c6c6',
        background: '#f9f9f9',
        primary: '#000000',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#303030',
        'on-primary-container': '#848484',
        'on-background': '#1b1b1b',
        'tertiary-fixed': '#e2e2e2',
        tertiary: '#000000',
        'on-tertiary-container': '#838484',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#1a1c1c',
        'on-error-container': '#93000a',
        'primary-container': '#1b1b1b',
        secondary: '#5e5e5e',
        'on-surface': '#1b1b1b',
        'on-surface-variant': '#4c4546',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#f1f1f1',
        'secondary-fixed': '#e4e2e2',
        'secondary-container': '#e1dfdf',
        'on-primary-fixed-variant': '#474747',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '2px',
        xl: '16px',
        md: '8px',
        sm: '4px',
        'margin-edge': '12px',
        gutter: '8px',
        lg: '12px',
      },
      fontFamily: {
        'label-mono': ['JetBrains Mono', 'monospace'],
        'body-sm': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'tabular-data': ['JetBrains Mono', 'monospace'],
        'headline-sm': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'label-mono': [
          '11px',
          {
            lineHeight: '14px',
            letterSpacing: '0.02em',
            fontWeight: '500',
          },
        ],
        'body-sm': [
          '12px',
          {
            lineHeight: '16px',
            letterSpacing: '0em',
            fontWeight: '400',
          },
        ],
        'body-md': [
          '13px',
          {
            lineHeight: '18px',
            letterSpacing: '0em',
            fontWeight: '400',
          },
        ],
        'tabular-data': [
          '12px',
          { lineHeight: '16px', fontWeight: '400' },
        ],
        'headline-sm': [
          '16px',
          {
            lineHeight: '20px',
            letterSpacing: '-0.01em',
            fontWeight: '600',
          },
        ],
      },
    },
  },
  plugins: [],
};
